### ISSUE TITLE
Bad link to StableMaterialMV checkpoint

### ISSUE THREAD

**Issue by jmunkberg** [yehonathanlitman/MaterialFusion#1]
Thanks for releasing the code and congrats to a nice paper!

The link to the MaterialFusionMV model checkpoint in the readme points to the NeRF Synthetic dataset. 
[StableMaterial-MV](https://drive.google.com/file/d/1qGP4rbKRJk1LLtffWmTpaZspDHjl1y_o/view?usp=sharing)

Link to [StableMaterial Dataset](https://drive.google.com/file/d/1qGP4rbKRJk1LLtffWmTpaZspDHjl1y_o/view?usp=sharing) is also wrong.

I found a good link in [download_stablematerial_ckpts.py](https://github.com/yehonathanlitman/MaterialFusion/tree/main/data/download_stablematerial_ckpts.py)

**Comment by yehonathanlitman** [comment]
Thanks for the heads up! The links have been updated
