### ISSUE TITLE
Release the training code of  the material diffusion prior

### ISSUE THREAD

**Issue by AVLwrh** [yehonathanlitman/MaterialFusion#3]
Thanks for your wonderful work! I also want to fine-tuning the stable diffusion model using my own dataset, so I would like to ask when the training code will be released. Or you can recommend some related papers. Thanks!!!

**Comment by yehonathanlitman** [comment]
Thank you for the kind feedback! I'll release the training code very soon, hopefully in conjunction with the rendering code.

**Comment by yehonathanlitman** [comment]
Training code and instructions have been added.
