### ISSUE TITLE
Loading the .blend file from BlenderVault dataset

### ISSUE THREAD

**Issue by shenghaoxie2020** [yehonathanlitman/MaterialFusion#5]
Hi! Thanks for your great work! Will you release code or details on how to load object views and material maps in .blend file from the BlenderVault dataset?

**Comment by yehonathanlitman** [comment]
Thank you for your interest! Apologies as things have been a bit hectic. I'll release the rendering + training code together soon

**Comment by shenghaoxie2020** [comment]
Thank you so much! Looking forward to the complete work.

**Comment by yehonathanlitman** [comment]
Rendering code as well as training code has been added! Instructions on how to render in Blender have also been added :)

**Comment by shxie2020** [comment]
Thanks a lot!
